language: java

jdk:
  - oraclejdk8

git:
  submodules: false

install:
  - mvn --settings scripts/mvn-release-settings.xml install -DskipTests -Dmaven.javadoc.skip=true -B -V

script:
  - mvn --settings scripts/mvn-release-settings.xml package -B -V
  - mvn --settings scripts/mvn-release-settings.xml javadoc:javadoc -B -V

before_deploy:
  - echo $GPG_SECRET_KEY | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

deploy:
  -
    skip_cleanup: true
    provider: script
    script: mvn --settings scripts/mvn-release-settings.xml deploy -Prelease -DskipTests -B -U
    on:
      tags: true
      # matches: X.Y.Z, X.Y.Z-A, X.Y.Z-RCA, X.Y.Z-A-B.C.D, X.Y.Z-A-B.C.D-E, X.Y.Z-RCA-B.C.D-E
      condition: "$TRAVIS_TAG =~ ^([[:digit:]]+\\.)+[[:digit:]]+(-(RC)?[[:digit:]]+)?(-([[:digit:]]+\\.)+[[:digit:]]+(-[[:digit:]]+)?)?$"
